### ISSUE TITLE
can not use library.

### ISSUE THREAD

**Issue by hpcreator** [shetmobile/MeowBottomNavigationJava#22]
As it supports jcentre in new project it is restricted to use. if i try to add jcentre in project it leads to manifest merger.
try to look over this issue and update library with latest version comparability.

**Comment by DangNguyen146** [comment]
I add jcenter() in settings.gradle 

```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
}
```
