### ISSUE TITLE
how to change icon when setOnClickMenuListener?

### ISSUE THREAD

**Issue by stnwj** [shetmobile/MeowBottomNavigationJava#3]

**Comment by amirbakhtiiarii** [comment]
خیلی کند هستش اندروید زیر 7 اصلا کار نمیکنه!!!

**Comment by amirbakhtiiarii** [comment]
thats very slowly, not working under 7 android!

**Comment by oneHamidreza** [comment]
از MeowBottomNavigation کتلین استفاده کنید.

**Comment by oneHamidreza** [comment]
https://github.com/oneHamidreza/MeowBottomNavigation
