### ISSUE TITLE
Keyboard is closed abruptly when try to type on editText field

### ISSUE THREAD

**Issue by iabduul7** [shetmobile/MeowBottomNavigationJava#5]
Please give me some solution, i am unable to open keyboard whenever i try to click on edittext field. 
respond to this issue please, as i am using this in my final year project and i liked this design very much and i do not want to give up on this.

**Comment by iabduul7** [comment]
I fixed the issue, the function

     bottomNavigation.setOnShowListener(new MeowBottomNavigation.ShowListener() {
            @Override
            public void onShowItem(MeowBottomNavigation.Model item) {

                Log.d("MainActivity", String.valueOf(item));
            }
        });

was causing the issue, for what I did was that I never used anything in this method except log.d(), but I must called it, i don't know why I think it is required. So, a simple fix to this keyboard problem is not to use anything in this method, but must call it.

**Comment by MegiasHack** [comment]
Thanks my friend.

> Arreglé el problema, la función
> 
> ```
>  bottomNavigation.setOnShowListener(new MeowBottomNavigation.ShowListener() {
>         @Override
>         public void onShowItem(MeowBottomNavigation.Model item) {
> 
>             Log.d("MainActivity", String.valueOf(item));
>         }
>     });
> ```
> 
> estaba causando el problema, porque lo que hice fue que nunca usé nada en este método excepto log.d (), pero debo llamarlo, no sé por qué creo que es necesario. Entonces, una solución simple a este problema del teclado es no usar nada en este método, sino que debe llamarlo.
