### ISSUE TITLE
set Selected Item Id by default or programmatically

### ISSUE THREAD

**Issue by meysamSM7** [shetmobile/MeowBottomNavigationJava#8]
hi,
i want a item clicked by default.
in this cods user should click on items for first time but i want one of them clicked by default or clicked programmatically

**Comment by meysamSM7** [comment]
bottomNavigation.show(TAB_ID)

**Comment by steve111MV** [comment]
My friend, the lib is very buggy. truly bad. Update

**Comment by oneHamidreza** [comment]
@steve111MV use kotlin library.

**Comment by brittle123** [comment]
@oneHamidreza  you should update this library aswel.
